snowflake_dbt_aws_project:
  outputs:
    dev:
      account: RDYHMIF-WYC13113
      database: AIRBNB
      password: AWSsnowflakedbtproject2025!
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: SANCHI293
      warehouse: COMPUTE_WH
  target: dev
